### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by tavinus** [estiloinfo/clip-itk#1]
Hi there!

Does anyone have a dependency list for this?
I am trying to compile on Debian 9, what do I need to install so I can complete it properly?
I have also tried on Centos7 and Fedora 27.
No success until now :(

What distro/version this is known to work?

Also, it would be nice to have a Readme.md page ;)

Cheers!
Gus

**Comment by estiloinfo** [comment]
Hi Gus, i trying  fix some compile errors, i am gentoo user.
you need bison 2 and compile as root with "make system"

Regards
Ricardo

**Comment by tavinus** [comment]
Hi,

**Edit** I compiled with `make local` and it seems fine (uses `/home/user` folder).

So far I was kind of able to compile on Fedora11 and Fedora20.
I am trying on Fedora25 now (compiler working but some libs still failing).

### My Install logs
Here is a list of the stuff I usually need to do/install so I can prepare to compile `Clip`

*This is messy, also includes other stuff I just wanted to install.*
Also, I selected the C Building and RPM building groups while installing Fedora, so this may not be complete.
#### set-up
```sh
# set locale before compiling
# ex: sudo localectl set-locale LANG=pt_BR.iso88591
# good idea to reboot after, but at least reconnect ssh

# I have also duplicated clip/charsets/8859-1.uni to clip/charsets/iso88591.uni
# so it can find my charset when compiling

# it is also a good idea to export the CLIPROOT variable
# eg.: export CLIPROOT=/home/user/src/clip-itk/cliproot
# You may also add that to /etc/profile or $HOME/.profile or $HOME/.bash_profile
```
#### yum (fedora20)
```sh
# if you want to select a group (ex: Building Tools)
yum groups list
# eg. : sudo yum groupinstall "Development Tools"

sudo yum install rsync git subversion cvs nano zip unzip wget curl bash-completion
sudo yum install time gpm flex bison gpm-devel flex-devel bison-devel
sudo yum install libpng libpng-devel
sudo yum install libpng12 libpng12-devel # for gd (still requires patches)
sudo yum install firebird-devel # for clip-interbase
sudo yum install python-pip
sudo yum install expat expat-devel expat-static
sudo yum install ncurses ncurses-devel ncurses-static ncurses-term
sudo yum install readline readline-devel readline-static
sudo yum install pth pth-devel
sudo yum install zlib zlib-devel zlib-static
sudo yum install libpng libpng-devel libjpeg-turbo libjpeg-turbo-devel
sudo yum install gtk2 gtk2-devel
sudo yum install banner
sudo yum install python2-pip
# sudo pip install --upgrade pip # no need
# sudo pip install flawfinder # used on another installer
# sudo yum install flawfinder # used on another installer
sudo yum install xclip
sudo yum install libzip libzip-devel
sudo yum install bzip2-devel
sudo yum install cryptopp cryptopp-devel cryptopp-progs
sudo yum install fcgi fcgi-devel
sudo yum install mariadb-devel # sudo yum install mysql-devel
sudo yum install unixODBC unixODBC-devel
sudo yum install postgresql postgresql-devel
sudo yum install libglade2 libglade2-devel
# sudo yum install pslib pslib-devel # not always present
sudo yum install pam pam-devel
sudo yum install tcp_wrappers tcp_wrappers-libs tcp_wrappers-devel
sudo yum install gd gd-devel
sudo yum install freetype freetype-devel
```
#### dnf (fedora25)
```sh
# if you want to select a group (ex: Building Tools)
dnf groups list
# eg. : sudo dnf groupinstall "Ferramentas de Desenvolvimento C e Bibliotecas"

sudo dnf update
sudo dnf install bash-completion sqlite
sudo dnf install rsync git subversion cvs nano zip unzip wget curl
sudo dnf install time gpm flex bison gpm-devel flex-devel bison-devel
sudo dnf install libpng libpng-devel
sudo dnf install python-pip
sudo dnf install gtk+-devel
sudo dnf install gtk+extra-devel
sudo dnf install expat expat-devel
sudo dnf install ncurses ncurses-devel ncurses-static ncurses-term
sudo dnf install ncurses-compat-libs
sudo dnf install readline readline-devel readline-static
sudo dnf install pth pth-devel
sudo dnf install zlib zlib-devel zlib-static
sudo dnf install libpng libpng-devel libjpeg-turbo libjpeg-turbo-devel
sudo dnf install libpng12 libpng12-devel # for gd (still requires patches)
sudo dnf install firebird-devel # for clip-interbase
sudo dnf install gtk2-devel
sudo dnf install banner # used by other installer
sudo dnf install flawfinder # used by other installer
sudo dnf install xclip
sudo dnf install libzip libzip-devel
sudo dnf install bzip2-devel
sudo dnf install cryptopp cryptopp-devel cryptopp-progs
sudo dnf install fcgi fcgi-devel
sudo dnf install mariadb-devel # sudo dnf install mysql-devel
sudo dnf install unixODBC unixODBC-devel
sudo dnf install postgresql postgresql-devel
sudo dnf install libglade2 libglade2-devel
sudo dnf install pslib pslib-devel
sudo dnf install pam pam-devel
sudo dnf install tcp_wrappers tcp_wrappers-libs tcp_wrappers-devel
sudo dnf install gd gd-devel
sudo dnf install freetype freetype-devel
```

I am still not 100% sure this is complete though.
And as I mentioned, stuff like `dbtcp` are abandoned and cannot be compiled on modern systems.

I am still not sure if I can 
1. set flags for not including a library 
2. OR if I should delete its folder
3. OR maybe change the Makefile to do nothing?

I have also changed a bunch of `cliplibs` sources so they would look for the `lib64` instead of `lib` folders. There was also some other stuff needing extra C Includes or some extra C flags. My version does not compile on 32bits anymore though (we would need some detection for the `lib/lib64` problem).

I may sync the changes I made with my fork later.

### My questions
1. ~~Should I use `make local` and `make system` ? What would you recommend?~~ 
    (you said `sudo make system`, but I can confirm `make local` works)
2. Can I set flags to NOT compile some stuff (no oracle for example) ? How to do this?
3. What modules/libraries do you compile with?

Cheers!
Gus

**PS:** *I made many edits...*
**PS2:** *Maybe you can find the corresponding gentoo packages*
**PS3:** *I still need to make a list of the libs that `fail`*

**Comment by estiloinfo** [comment]
This is a clone of https://sourceforge.net/projects/clip-itk/

I try compile make local but compilation fail when build kamache prg, but no error in make system.
still do not try to fix it

I compile all libs and modules, some with error (oracle) but not critic. If you can't compile same libs you need edit Makefile o Makefile.in, i am not expert in build scripts and structure.The compilation scripts are ugly

I only use this libs 
libclip-postgres.so => /usr/lib64/libclip-postgres.so (0x00007f9ad9928000)
libclip-crypto.so => /usr/lib64/libclip-crypto.so (0x00007f9ad9720000)
libclip.so => /usr/lib64/libclip.so (0x00007f9ad92a0000)

This is my build libraries, but I do not know if they all work
libclip-bzip2.so
libclip-codb.so
libclip-crypto.so
libclip-glade2.so
libclip-gtk2.so
libclip-gzip.so
libclip-mysql.so
libclip-nanfor.so
libclip-netto.so
libclip-postgres.so
libclip-postscript.so
libclip-r2d2.so
libclip-rtf.so
libclip-ui.so
libclip-xml.so
libclip.so

When run make system LANG set to C but not at make local.

make local set CLIPROOT=~/cliproot if is not defined.

I have a symbolic link /usr/lib of /usr/lib64  

if you can build  make local  &> build.log and send me via pastebin i try help you

Regards
Ricardo

**Comment by tavinus** [comment]
Ok, for the most part my post above is correct on the dependencies and all.
I have also added some other stuff that I found out was needed just now.

Please note that if you compile stuff manually and use `make install`, 
**YOU WILL NEED TO SET YOUR `$CLIPROOT` BEFORE USING `make install`** 
or things may go to the wrong places.

#### I was able to compile ALL libs except for
 - clip-dbtcp (abandoned)
 - clip-gtkextra (uses old/deprecated gtkextra)
 - clip-oracle (I didn't bother to install it to check)

There were a few libs that I had to edit the `Makefile.in` and/or `configure` file.
Those will NOT compile without fixes (you can count 6 or more there).
I may post the changes soon.

#### To enable/disable libraries
Edit the variable `dirs` on `cliplibs/Makefile`.
Just remove or add dirs there. Mine is currently looking like this:
```Makefile
dirs = clip-gzip clip-bzip2 clip-crypto clip-gd clip-fcgi \
       clip-gtk2 clip-cti clip-fw clip-interbase \
       clip-mysql clip-postgres clip-odbc \
       clip-com clip-oasis clip-rtf clip-r2d2 \
       clip-xml clip-glade2 clip-ui clip-postscript

# DISABLED: clip-oracle clip-gtk clip-gtkextra
```
#### To test/compile each lib on its own
```sh
# Remember to export CLIPROOT before, eg:
export CLIPROOT=/home/user/clip-itk/cliproot
```
Enter each cliplib/clip-`<LIB>` folder and use:
 - `make` to compile
 - `make clean` to clean
 - `make install` to install to `$CLIPROOT`

#### The Kamache mistery
The `kamache.prg` problem is quite annoying because I can compile kamache from its folder and from the /prg folder without problems (using just `make`). But then when kamache is compiled from the root folder `make local` (or `make system`) it always fails. 

The compile line is identical on both cases (I checked), not sure if there is an environment var change that the compilation doesn't like or what.

If you are able to compile kamache from its folder (or the prg folder), you can tell the main Makefile to not clean the program and then it will not fail. Which is what I did.

So I first tried to **disable CLEAN** on `make local` (or `make system`) on the root folder's Makefile. That did not seem to prevent the clean on kamache though, so I added the `-noclean` parameter to them as well and that did the trick

**Makefile example** with clean target commented and `-noclean` parameter
```Makefile
user local: #clean
        ./mklocal -noclean

system: #clean
        ./mklocal -noclean -release
``` 
And then I finally have it to finish without errors.
I spent a few hours on the kamache thing and it makes no sense to me.
I wonder if kamache runs before it should and then we don't have the clip libraries it needs available (some kind of bootstrap error?).

So, in a nutshell, make these "no-clean" changes, then go inside the `prg` folder and run `make`, then go back to the `clip-itk` folder and run `make local` (or `sudo make system`) and it should go past kamache.

Anyways... this is my current status and progress.
Like I said, my changes do not respect 32bit systems at all, so my copy will NOT compile on 32bit.

**BTW, it is probably a very bad idea to have your `/usr/lib` symlinked to `usr/lib64`. 
On most 64bit systems you have both folders placed.** 
It is normal and acceptable to install 32bit libraries on 64bit systems (but not the other way around). 
So if you really want to do this, it would be better to create the `/usr/lib` folder and then just symlink stuff needed in there. For instance, if you install a 32bit library, it will end up in the lib64 folder.

Cheers
Gus

**PS1:** I tried to `sudo make system` (with clean enabled) and I still got the same "kamache problem". Thank god for VM snapshots :)

**Comment by tavinus** [comment]
# tested now, Kamache does not work! don't do this
## Fixing the `kamache` problem
**The INcorrect way*

So, it seems like for some reason the flag `-lclip-r2d2` fails when running in the middle of the recipe (but not when you run make from the kamache folder). The clean is unlinking it maybe?


Change the file
```
clip-itk/prg/kamache/Makefile
```
I have comented the flag out and changed to a reference of the library file.
```Makefile
CLIPLIBS  = -lclip-codb -l:libclip-r2d2.so  # -lclip-r2d2
```
~~And now compiles past kamache even from `make local` or `sudo make system`
And you can return the "auto-clean" stuff if you have disabled it~~

Compiles but does not work.

Cheers!
Gus

**Comment by estiloinfo** [comment]
Hi Gus, i cleanup all (similar to git clone),  make local (error on kamache), then export CLIPROT=/home/ricardo/cliproot and go to kamache dir, execute make and compile works, then test kamache and work.   That was always my problem with make local but still do not try to fix it.

In my system have lib64 and lib32 dir, of course the libraries should be installed in the corresponding directory. 

I agree with disabling obsolete libraries

I'm going to start working on fixing clip-com, changing pth to npth (in gentoo pth not exist more)

What version of ncurses do you have installed?

Regards
Rick

**Comment by tavinus** [comment]
After all we hit a big wall.
This is not looking good.

Some big routines are generating a `.c` file with an array that has like, 16 items PER LINE and TEN THOUSAND lines. Because of that GCC complains and does not compile (.po file is too big). It is ~5 times more than Plain C accepts.

I also have no idea why the pre-compiler stuffs everything as INTs in a SINGLE ARRAY.

The same Makefile / `.prg` files compile fine on an older system with old-school itk Clip 1.1.16.0.
It is an Amazon Linux (Fedora) that has been operating for many years.
I have enabled the flag to preserve .c files on the older version but it did not comply. Found no .c files to compare.

About ncurses. As you can see I tried this all the way from Fedora 11 to 27.
Ncurses became a problem on Fedora25, but they have a package `ncurses-compat-libs` that solves it (not sure if it symlinks or what). Before that I just used whatever nurses-devel they had.

I have updated my github but it does not seem to be working from there.
I have used a ZIP that is supped to be the same as github (checked many times) and that one works.
I may need to re-estage my fork,

Cheers!
Gus

**Comment by estiloinfo** [comment]
Fix comilation gcc-1x, make comilation report and deps need
Tested in: gentoo, debian 10/11
